import React, { useState } from "react";
import { useEffect } from "react";
import styles from "../../styles/socials.module.scss";
import Header from "../Header";
export default function SocialsPage() {
  const data = [
    {
      created_at: "Sat Jun 18 16:27:39 +0000 2022",
      id: 1538196755396694000,
      id_str: "1538196755396694017",
      full_text:
        "RT @Rofan_always: @sajnani_rohit Hiiii Friend plzz follow mini FC @Imro_fanclub 🥰 becz it needs Hitman &amp; Mumbai Indians lovers support plz…",
      truncated: false,
      display_text_range: [0, 143],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "Rofan_always",
            name: "Rishabh_45",
            id: 1436753112379768800,
            id_str: "1436753112379768835",
            indices: [3, 16],
          },
          {
            screen_name: "sajnani_rohit",
            name: "Rohit Sajnani",
            id: 1110963711173247000,
            id_str: "1110963711173246976",
            indices: [18, 32],
          },
          {
            screen_name: "Imro_fanclub",
            name: "Rohit Sharma Fanclub India",
            id: 1306631691444736000,
            id_str: "1306631691444736001",
            indices: [66, 79],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 1110963711173247000,
        id_str: "1110963711173246976",
        name: "Rohit Sajnani",
        screen_name: "sajnani_rohit",
        location: "",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 7,
        friends_count: 39,
        listed_count: 0,
        created_at: "Wed Mar 27 17:56:04 +0000 2019",
        favourites_count: 1258,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 109,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1110963860423540744/80PRWkGu_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1110963860423540744/80PRWkGu_normal.jpg",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      retweeted_status: {
        created_at: "Wed Mar 23 16:49:29 +0000 2022",
        id: 1506674504621498400,
        id_str: "1506674504621498368",
        full_text:
          "@sajnani_rohit Hiiii Friend plzz follow mini FC @Imro_fanclub 🥰 becz it needs Hitman &amp; Mumbai Indians lovers support plz friend 💙\n\n&amp; If u want Follow back then I'll give you but please follow FC @Imro_fanclub pls 🙏 !!",
        truncated: false,
        display_text_range: [0, 225],
        entities: {
          hashtags: [],
          symbols: [],
          user_mentions: [
            {
              screen_name: "sajnani_rohit",
              name: "Rohit Sajnani",
              id: 1110963711173247000,
              id_str: "1110963711173246976",
              indices: [0, 14],
            },
            {
              screen_name: "Imro_fanclub",
              name: "Rohit Sharma Fanclub India",
              id: 1306631691444736000,
              id_str: "1306631691444736001",
              indices: [48, 61],
            },
            {
              screen_name: "Imro_fanclub",
              name: "Rohit Sharma Fanclub India",
              id: 1306631691444736000,
              id_str: "1306631691444736001",
              indices: [203, 216],
            },
          ],
          urls: [],
        },
        metadata: {
          iso_language_code: "en",
          result_type: "recent",
        },
        source:
          '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: 1110963711173247000,
        in_reply_to_user_id_str: "1110963711173246976",
        in_reply_to_screen_name: "sajnani_rohit",
        user: {
          id: 1436753112379768800,
          id_str: "1436753112379768835",
          name: "Rishabh_45",
          screen_name: "Rofan_always",
          location: "",
          description:
            "A die hard fan of  @Imro45 🥰, and my passion is making memes 😌",
          url: null,
          entities: {
            description: {
              urls: [],
            },
          },
          protected: false,
          followers_count: 2777,
          friends_count: 3466,
          listed_count: 0,
          created_at: "Sat Sep 11 18:07:10 +0000 2021",
          favourites_count: 3981,
          utc_offset: null,
          time_zone: null,
          geo_enabled: false,
          verified: false,
          statuses_count: 35221,
          lang: null,
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: "F5F8FA",
          profile_background_image_url: null,
          profile_background_image_url_https: null,
          profile_background_tile: false,
          profile_image_url:
            "http://pbs.twimg.com/profile_images/1534956187963527169/Gja5R9hk_normal.jpg",
          profile_image_url_https:
            "https://pbs.twimg.com/profile_images/1534956187963527169/Gja5R9hk_normal.jpg",
          profile_banner_url:
            "https://pbs.twimg.com/profile_banners/1436753112379768835/1647970146",
          profile_link_color: "1DA1F2",
          profile_sidebar_border_color: "C0DEED",
          profile_sidebar_fill_color: "DDEEF6",
          profile_text_color: "333333",
          profile_use_background_image: true,
          has_extended_profile: true,
          default_profile: true,
          default_profile_image: false,
          following: null,
          follow_request_sent: null,
          notifications: null,
          translator_type: "none",
          withheld_in_countries: [],
        },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 1,
        favorite_count: 2,
        favorited: false,
        retweeted: false,
        lang: "en",
      },
      is_quote_status: false,
      retweet_count: 1,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 14:34:48 +0000 2022",
      id: 1538168355231658000,
      id_str: "1538168355231657986",
      full_text:
        "@Bo_Hoogland imagine mumbai indians partners with global esports and you see skillz dancing like in the jio commercials 💀",
      truncated: false,
      display_text_range: [13, 121],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "Bo_Hoogland",
            name: "BoDork",
            id: 740237543409655800,
            id_str: "740237543409655808",
            indices: [0, 12],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: 1538159549470883800,
      in_reply_to_status_id_str: "1538159549470883844",
      in_reply_to_user_id: 740237543409655800,
      in_reply_to_user_id_str: "740237543409655808",
      in_reply_to_screen_name: "Bo_Hoogland",
      user: {
        id: 1129700491649093600,
        id_str: "1129700491649093632",
        name: "Paracosm",
        screen_name: "pracosm",
        location: "Mumbai ",
        description:
          "16 ; electrical baiter for @Outcastsesports                          \n                \nmaking some videos: https://t.co/wZaJUfy2MP",
        url: "https://t.co/IcNKcQFGat",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/IcNKcQFGat",
                expanded_url: "https://youtu.be/6HRC0vA6z_w",
                display_url: "youtu.be/6HRC0vA6z_w",
                indices: [0, 23],
              },
            ],
          },
          description: {
            urls: [
              {
                url: "https://t.co/wZaJUfy2MP",
                expanded_url: "http://youtube.com/c/paracos",
                display_url: "youtube.com/c/paracos",
                indices: [107, 130],
              },
            ],
          },
        },
        protected: false,
        followers_count: 163,
        friends_count: 66,
        listed_count: 0,
        created_at: "Sat May 18 10:49:20 +0000 2019",
        favourites_count: 9178,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 2903,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1519381199696789505/tq-A1_q6_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1519381199696789505/tq-A1_q6_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/1129700491649093632/1651985530",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 14,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 14:30:36 +0000 2022",
      id: 1538167299164627000,
      id_str: "1538167299164626944",
      full_text:
        "RT @Ro_45_Mi: Mumbai Indians supPorters for today mAtcH #MIvsDC  @mipaltan @RCBTweets @imVkohli @faf1307 @Gmaxi_32 https://t.co/wxfNw63kiE",
      truncated: false,
      display_text_range: [0, 138],
      entities: {
        hashtags: [
          {
            text: "MIvsDC",
            indices: [56, 63],
          },
        ],
        symbols: [],
        user_mentions: [
          {
            screen_name: "Ro_45_Mi",
            name: "Saurabh Ganguly",
            id: 1042215920293208000,
            id_str: "1042215920293208066",
            indices: [3, 12],
          },
          {
            screen_name: "mipaltan",
            name: "Mumbai Indians",
            id: 106345557,
            id_str: "106345557",
            indices: [65, 74],
          },
          {
            screen_name: "RCBTweets",
            name: "Royal Challengers Bangalore",
            id: 70931004,
            id_str: "70931004",
            indices: [75, 85],
          },
          {
            screen_name: "imVkohli",
            name: "Virat Kohli",
            id: 71201743,
            id_str: "71201743",
            indices: [86, 95],
          },
          {
            screen_name: "faf1307",
            name: "Faf Du Plessis",
            id: 135180139,
            id_str: "135180139",
            indices: [96, 104],
          },
          {
            screen_name: "Gmaxi_32",
            name: "Glenn Maxwell",
            id: 271292659,
            id_str: "271292659",
            indices: [105, 114],
          },
        ],
        urls: [],
        media: [
          {
            id: 1527902073677033500,
            id_str: "1527902073677033472",
            indices: [115, 138],
            media_url: "http://pbs.twimg.com/media/FTQy10EaMAAONXc.jpg",
            media_url_https: "https://pbs.twimg.com/media/FTQy10EaMAAONXc.jpg",
            url: "https://t.co/wxfNw63kiE",
            display_url: "pic.twitter.com/wxfNw63kiE",
            expanded_url:
              "https://twitter.com/Ro_45_Mi/status/1527902090890125312/photo/1",
            type: "photo",
            sizes: {
              thumb: {
                w: 150,
                h: 150,
                resize: "crop",
              },
              small: {
                w: 680,
                h: 610,
                resize: "fit",
              },
              medium: {
                w: 1080,
                h: 969,
                resize: "fit",
              },
              large: {
                w: 1080,
                h: 969,
                resize: "fit",
              },
            },
            source_status_id: 1527902090890125300,
            source_status_id_str: "1527902090890125312",
            source_user_id: 1042215920293208000,
            source_user_id_str: "1042215920293208066",
          },
        ],
      },
      extended_entities: {
        media: [
          {
            id: 1527902073677033500,
            id_str: "1527902073677033472",
            indices: [115, 138],
            media_url: "http://pbs.twimg.com/media/FTQy10EaMAAONXc.jpg",
            media_url_https: "https://pbs.twimg.com/media/FTQy10EaMAAONXc.jpg",
            url: "https://t.co/wxfNw63kiE",
            display_url: "pic.twitter.com/wxfNw63kiE",
            expanded_url:
              "https://twitter.com/Ro_45_Mi/status/1527902090890125312/photo/1",
            type: "photo",
            sizes: {
              thumb: {
                w: 150,
                h: 150,
                resize: "crop",
              },
              small: {
                w: 680,
                h: 610,
                resize: "fit",
              },
              medium: {
                w: 1080,
                h: 969,
                resize: "fit",
              },
              large: {
                w: 1080,
                h: 969,
                resize: "fit",
              },
            },
            source_status_id: 1527902090890125300,
            source_status_id_str: "1527902090890125312",
            source_user_id: 1042215920293208000,
            source_user_id_str: "1042215920293208066",
          },
        ],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 1471863415408787500,
        id_str: "1471863415408787457",
        name: "KATTAR VIRAT BHAKT × TIGER 🚩",
        screen_name: "AbinashTiwari_1",
        location: "Sambalpur , Odisha ",
        description: "Cricket Fan...",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 1138,
        friends_count: 1396,
        listed_count: 0,
        created_at: "Fri Dec 17 15:22:49 +0000 2021",
        favourites_count: 17049,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 11325,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1477249379769585664/mocK3Sy__normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1477249379769585664/mocK3Sy__normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/1471863415408787457/1654662531",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      retweeted_status: {
        created_at: "Sat May 21 06:40:20 +0000 2022",
        id: 1527902090890125300,
        id_str: "1527902090890125312",
        full_text:
          "Mumbai Indians supPorters for today mAtcH #MIvsDC  @mipaltan @RCBTweets @imVkohli @faf1307 @Gmaxi_32 https://t.co/wxfNw63kiE",
        truncated: false,
        display_text_range: [0, 100],
        entities: {
          hashtags: [
            {
              text: "MIvsDC",
              indices: [42, 49],
            },
          ],
          symbols: [],
          user_mentions: [
            {
              screen_name: "mipaltan",
              name: "Mumbai Indians",
              id: 106345557,
              id_str: "106345557",
              indices: [51, 60],
            },
            {
              screen_name: "RCBTweets",
              name: "Royal Challengers Bangalore",
              id: 70931004,
              id_str: "70931004",
              indices: [61, 71],
            },
            {
              screen_name: "imVkohli",
              name: "Virat Kohli",
              id: 71201743,
              id_str: "71201743",
              indices: [72, 81],
            },
            {
              screen_name: "faf1307",
              name: "Faf Du Plessis",
              id: 135180139,
              id_str: "135180139",
              indices: [82, 90],
            },
            {
              screen_name: "Gmaxi_32",
              name: "Glenn Maxwell",
              id: 271292659,
              id_str: "271292659",
              indices: [91, 100],
            },
          ],
          urls: [],
          media: [
            {
              id: 1527902073677033500,
              id_str: "1527902073677033472",
              indices: [101, 124],
              media_url: "http://pbs.twimg.com/media/FTQy10EaMAAONXc.jpg",
              media_url_https:
                "https://pbs.twimg.com/media/FTQy10EaMAAONXc.jpg",
              url: "https://t.co/wxfNw63kiE",
              display_url: "pic.twitter.com/wxfNw63kiE",
              expanded_url:
                "https://twitter.com/Ro_45_Mi/status/1527902090890125312/photo/1",
              type: "photo",
              sizes: {
                thumb: {
                  w: 150,
                  h: 150,
                  resize: "crop",
                },
                small: {
                  w: 680,
                  h: 610,
                  resize: "fit",
                },
                medium: {
                  w: 1080,
                  h: 969,
                  resize: "fit",
                },
                large: {
                  w: 1080,
                  h: 969,
                  resize: "fit",
                },
              },
            },
          ],
        },
        extended_entities: {
          media: [
            {
              id: 1527902073677033500,
              id_str: "1527902073677033472",
              indices: [101, 124],
              media_url: "http://pbs.twimg.com/media/FTQy10EaMAAONXc.jpg",
              media_url_https:
                "https://pbs.twimg.com/media/FTQy10EaMAAONXc.jpg",
              url: "https://t.co/wxfNw63kiE",
              display_url: "pic.twitter.com/wxfNw63kiE",
              expanded_url:
                "https://twitter.com/Ro_45_Mi/status/1527902090890125312/photo/1",
              type: "photo",
              sizes: {
                thumb: {
                  w: 150,
                  h: 150,
                  resize: "crop",
                },
                small: {
                  w: 680,
                  h: 610,
                  resize: "fit",
                },
                medium: {
                  w: 1080,
                  h: 969,
                  resize: "fit",
                },
                large: {
                  w: 1080,
                  h: 969,
                  resize: "fit",
                },
              },
            },
          ],
        },
        metadata: {
          iso_language_code: "en",
          result_type: "recent",
        },
        source:
          '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
          id: 1042215920293208000,
          id_str: "1042215920293208066",
          name: "Saurabh Ganguly",
          screen_name: "Ro_45_Mi",
          location: "Bihar, India",
          description:
            "Life is like riding a bike🚴: To keep your balance⚖️, you must keep moving",
          url: null,
          entities: {
            description: {
              urls: [],
            },
          },
          protected: false,
          followers_count: 623,
          friends_count: 859,
          listed_count: 0,
          created_at: "Wed Sep 19 00:56:53 +0000 2018",
          favourites_count: 8818,
          utc_offset: null,
          time_zone: null,
          geo_enabled: true,
          verified: false,
          statuses_count: 1001,
          lang: null,
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: "F5F8FA",
          profile_background_image_url: null,
          profile_background_image_url_https: null,
          profile_background_tile: false,
          profile_image_url:
            "http://pbs.twimg.com/profile_images/1405790142556635137/UzipZJrn_normal.jpg",
          profile_image_url_https:
            "https://pbs.twimg.com/profile_images/1405790142556635137/UzipZJrn_normal.jpg",
          profile_banner_url:
            "https://pbs.twimg.com/profile_banners/1042215920293208066/1649389320",
          profile_link_color: "1DA1F2",
          profile_sidebar_border_color: "C0DEED",
          profile_sidebar_fill_color: "DDEEF6",
          profile_text_color: "333333",
          profile_use_background_image: true,
          has_extended_profile: true,
          default_profile: true,
          default_profile_image: false,
          following: null,
          follow_request_sent: null,
          notifications: null,
          translator_type: "none",
          withheld_in_countries: [],
        },
        geo: null,
        coordinates: null,
        place: {
          id: "04c6273e444bd1e3",
          url: "https://api.twitter.com/1.1/geo/id/04c6273e444bd1e3.json",
          place_type: "city",
          name: "Tribeniganj",
          full_name: "Tribeniganj, India",
          country_code: "IN",
          country: "India",
          contained_within: [],
          bounding_box: {
            type: "Polygon",
            coordinates: [
              [
                [86.864893, 26.108774],
                [86.910218, 26.108774],
                [86.910218, 26.148761],
                [86.864893, 26.148761],
              ],
            ],
          },
          attributes: {},
        },
        contributors: null,
        is_quote_status: false,
        retweet_count: 296,
        favorite_count: 6963,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: "en",
      },
      is_quote_status: false,
      retweet_count: 296,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 14:14:47 +0000 2022",
      id: 1538163319818682400,
      id_str: "1538163319818682369",
      full_text:
        "RT @ittzz_spidey: Mumbai Indians playing on their home ground &amp; chants of RCB RCB RCB &amp; Virat Virat Virat going on.!The value of Virat Kohl…",
      truncated: false,
      display_text_range: [0, 148],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "ittzz_spidey",
            name: "Deep Point",
            id: 1355212874981855200,
            id_str: "1355212874981855233",
            indices: [3, 16],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 1295681899352875000,
        id_str: "1295681899352875008",
        name: "SAMRIDHA BANERJEE OFFICIAL 🇮🇳",
        screen_name: "SAMRIDHABANERJ2",
        location: "",
        description:
          "THE WORLD NEEDS TO BE CHANGED. I'M HERE TO CHANGE IT AND FOR THAT I HAVE TO CONTRIBUTE SOMETHING TO THE WORLD LIKE A GOOD HUMAN. SUBSCRIBE TO MY YOUTUBE.👇👇👇",
        url: "https://t.co/boiH9KnYq8",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/boiH9KnYq8",
                expanded_url:
                  "https://www.youtube.com/channel/UCec49P54-QSCOyQ_oRVX5Aw",
                display_url: "youtube.com/channel/UCec49…",
                indices: [0, 23],
              },
            ],
          },
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 675,
        friends_count: 4982,
        listed_count: 2,
        created_at: "Tue Aug 18 11:20:26 +0000 2020",
        favourites_count: 40581,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 32953,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1492815891653750788/N_jr0z_u_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1492815891653750788/N_jr0z_u_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/1295681899352875008/1644750020",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      retweeted_status: {
        created_at: "Sat May 21 17:52:04 +0000 2022",
        id: 1528071137577447400,
        id_str: "1528071137577447426",
        full_text:
          "Mumbai Indians playing on their home ground &amp; chants of RCB RCB RCB &amp; Virat Virat Virat going on.!The value of Virat Kohli.!",
        truncated: false,
        display_text_range: [0, 132],
        entities: {
          hashtags: [],
          symbols: [],
          user_mentions: [],
          urls: [],
        },
        metadata: {
          iso_language_code: "en",
          result_type: "recent",
        },
        source:
          '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
          id: 1355212874981855200,
          id_str: "1355212874981855233",
          name: "Deep Point",
          screen_name: "ittzz_spidey",
          location: "India ",
          description:
            "Sports Enthusiast..Stats,Analysis,Memes,threads,about cricket..Loves talking about cricket...Tweet funny.!",
          url: null,
          entities: {
            description: {
              urls: [],
            },
          },
          protected: false,
          followers_count: 8527,
          friends_count: 794,
          listed_count: 24,
          created_at: "Fri Jan 29 17:55:14 +0000 2021",
          favourites_count: 2963,
          utc_offset: null,
          time_zone: null,
          geo_enabled: true,
          verified: false,
          statuses_count: 7982,
          lang: null,
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: "F5F8FA",
          profile_background_image_url: null,
          profile_background_image_url_https: null,
          profile_background_tile: false,
          profile_image_url:
            "http://pbs.twimg.com/profile_images/1472088480175964160/ba6pdF9j_normal.jpg",
          profile_image_url_https:
            "https://pbs.twimg.com/profile_images/1472088480175964160/ba6pdF9j_normal.jpg",
          profile_banner_url:
            "https://pbs.twimg.com/profile_banners/1355212874981855233/1653911404",
          profile_link_color: "1DA1F2",
          profile_sidebar_border_color: "C0DEED",
          profile_sidebar_fill_color: "DDEEF6",
          profile_text_color: "333333",
          profile_use_background_image: true,
          has_extended_profile: true,
          default_profile: true,
          default_profile_image: false,
          following: null,
          follow_request_sent: null,
          notifications: null,
          translator_type: "none",
          withheld_in_countries: [],
        },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 895,
        favorite_count: 8710,
        favorited: false,
        retweeted: false,
        lang: "en",
      },
      is_quote_status: false,
      retweet_count: 895,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 13:53:39 +0000 2022",
      id: 1538157999729954800,
      id_str: "1538157999729954817",
      full_text:
        "@gaudiya_surya I red in local hindi news during 2008 Mumbai MNS attack on north Indians.",
      truncated: false,
      display_text_range: [15, 88],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "gaudiya_surya",
            name: "গৌড়ীয়/गौड़ीय Surya 🇮🇳",
            id: 1394568444524126200,
            id_str: "1394568444524126218",
            indices: [0, 14],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: 1538151858174316500,
      in_reply_to_status_id_str: "1538151858174316544",
      in_reply_to_user_id: 1394568444524126200,
      in_reply_to_user_id_str: "1394568444524126218",
      in_reply_to_screen_name: "gaudiya_surya",
      user: {
        id: 1317153128462966800,
        id_str: "1317153128462966785",
        name: "बजरंग Bhakt 🇮🇳 🚩",
        screen_name: "ThinkTankerNS",
        location: "",
        description: "Nation/Environment/Sanatan🕉🚩",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 280,
        friends_count: 1535,
        listed_count: 0,
        created_at: "Fri Oct 16 17:20:33 +0000 2020",
        favourites_count: 74873,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 36011,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1419336684332675072/0t_3kbMn_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1419336684332675072/0t_3kbMn_normal.jpg",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 13:25:17 +0000 2022",
      id: 1538150860458381300,
      id_str: "1538150860458381312",
      full_text:
        "@ayan_acharya13 I think Kumar Kartikeya will be getting an India A call up soon. Plus he us with Mumbai Indians",
      truncated: false,
      display_text_range: [16, 111],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "ayan_acharya13",
            name: "Ayan",
            id: 870975513266802700,
            id_str: "870975513266802688",
            indices: [0, 15],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: 1538148711938683000,
      in_reply_to_status_id_str: "1538148711938682880",
      in_reply_to_user_id: 870975513266802700,
      in_reply_to_user_id_str: "870975513266802688",
      in_reply_to_screen_name: "ayan_acharya13",
      user: {
        id: 50619514,
        id_str: "50619514",
        name: "SK Anand",
        screen_name: "di_an",
        location: "New Delhi, India",
        description:
          "The day Mind & Intellect becomes one Team..@theHockeyIndia /@MumbaiCricAssoc/ Vettel\n A-Political /Usual Caveats on RT& Sharing of Articles",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 1022,
        friends_count: 479,
        listed_count: 39,
        created_at: "Thu Jun 25 11:27:15 +0000 2009",
        favourites_count: 259,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 123113,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "EDECE9",
        profile_background_image_url:
          "http://abs.twimg.com/images/themes/theme3/bg.gif",
        profile_background_image_url_https:
          "https://abs.twimg.com/images/themes/theme3/bg.gif",
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1406948634688593921/LgTD3z5N_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1406948634688593921/LgTD3z5N_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/50619514/1637766086",
        profile_link_color: "981CEB",
        profile_sidebar_border_color: "D3D2CF",
        profile_sidebar_fill_color: "E3E2DE",
        profile_text_color: "634047",
        profile_use_background_image: false,
        has_extended_profile: false,
        default_profile: false,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 13:10:20 +0000 2022",
      id: 1538147098859688000,
      id_str: "1538147098859687936",
      full_text:
        "RT @dhaikilokatweet: mumbai indians \nbefore 2022                      in 2022 https://t.co/EWsWU6y5Wq",
      truncated: false,
      display_text_range: [0, 101],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "dhaikilokatweet",
            name: "Arun Lol",
            id: 88138010,
            id_str: "88138010",
            indices: [3, 19],
          },
        ],
        urls: [],
        media: [
          {
            id: 1537877966469726200,
            id_str: "1537877966469726208",
            indices: [78, 101],
            media_url:
              "http://pbs.twimg.com/ext_tw_video_thumb/1537877966469726208/pu/img/jPdRVIUZXPi48w3Q.jpg",
            media_url_https:
              "https://pbs.twimg.com/ext_tw_video_thumb/1537877966469726208/pu/img/jPdRVIUZXPi48w3Q.jpg",
            url: "https://t.co/EWsWU6y5Wq",
            display_url: "pic.twitter.com/EWsWU6y5Wq",
            expanded_url:
              "https://twitter.com/dhaikilokatweet/status/1537877998514237442/video/1",
            type: "photo",
            sizes: {
              thumb: {
                w: 150,
                h: 150,
                resize: "crop",
              },
              small: {
                w: 680,
                h: 680,
                resize: "fit",
              },
              large: {
                w: 1080,
                h: 1080,
                resize: "fit",
              },
              medium: {
                w: 1080,
                h: 1080,
                resize: "fit",
              },
            },
            source_status_id: 1537877998514237400,
            source_status_id_str: "1537877998514237442",
            source_user_id: 88138010,
            source_user_id_str: "88138010",
          },
        ],
      },
      extended_entities: {
        media: [
          {
            id: 1537877966469726200,
            id_str: "1537877966469726208",
            indices: [78, 101],
            media_url:
              "http://pbs.twimg.com/ext_tw_video_thumb/1537877966469726208/pu/img/jPdRVIUZXPi48w3Q.jpg",
            media_url_https:
              "https://pbs.twimg.com/ext_tw_video_thumb/1537877966469726208/pu/img/jPdRVIUZXPi48w3Q.jpg",
            url: "https://t.co/EWsWU6y5Wq",
            display_url: "pic.twitter.com/EWsWU6y5Wq",
            expanded_url:
              "https://twitter.com/dhaikilokatweet/status/1537877998514237442/video/1",
            type: "video",
            sizes: {
              thumb: {
                w: 150,
                h: 150,
                resize: "crop",
              },
              small: {
                w: 680,
                h: 680,
                resize: "fit",
              },
              large: {
                w: 1080,
                h: 1080,
                resize: "fit",
              },
              medium: {
                w: 1080,
                h: 1080,
                resize: "fit",
              },
            },
            source_status_id: 1537877998514237400,
            source_status_id_str: "1537877998514237442",
            source_user_id: 88138010,
            source_user_id_str: "88138010",
            video_info: {
              aspect_ratio: [1, 1],
              duration_millis: 10495,
              variants: [
                {
                  bitrate: 1280000,
                  content_type: "video/mp4",
                  url: "https://video.twimg.com/ext_tw_video/1537877966469726208/pu/vid/720x720/rubQMRDlOrmvdaKt.mp4?tag=12",
                },
                {
                  content_type: "application/x-mpegURL",
                  url: "https://video.twimg.com/ext_tw_video/1537877966469726208/pu/pl/VOk24PSxFWAyX7MU.m3u8?tag=12&container=fmp4",
                },
                {
                  bitrate: 832000,
                  content_type: "video/mp4",
                  url: "https://video.twimg.com/ext_tw_video/1537877966469726208/pu/vid/540x540/iwQ5W7y1ABn1NXsC.mp4?tag=12",
                },
                {
                  bitrate: 432000,
                  content_type: "video/mp4",
                  url: "https://video.twimg.com/ext_tw_video/1537877966469726208/pu/vid/320x320/Hb-eo0MYZjxyxHJq.mp4?tag=12",
                },
              ],
            },
            additional_media_info: {
              monetizable: false,
              source_user: {
                id: 88138010,
                id_str: "88138010",
                name: "Arun Lol",
                screen_name: "dhaikilokatweet",
                location: "",
                description: "save RR fans only 3 left https://t.co/yxNp6zSgSz",
                url: null,
                entities: {
                  description: {
                    urls: [
                      {
                        url: "https://t.co/yxNp6zSgSz",
                        expanded_url: "http://instagram.com/arun__lol",
                        display_url: "instagram.com/arun__lol",
                        indices: [25, 48],
                      },
                    ],
                  },
                },
                protected: false,
                followers_count: 41618,
                friends_count: 543,
                listed_count: 135,
                created_at: "Sat Nov 07 07:28:21 +0000 2009",
                favourites_count: 56790,
                utc_offset: null,
                time_zone: null,
                geo_enabled: true,
                verified: false,
                statuses_count: 99621,
                lang: null,
                contributors_enabled: false,
                is_translator: false,
                is_translation_enabled: false,
                profile_background_color: "FFF04D",
                profile_background_image_url:
                  "http://abs.twimg.com/images/themes/theme19/bg.gif",
                profile_background_image_url_https:
                  "https://abs.twimg.com/images/themes/theme19/bg.gif",
                profile_background_tile: false,
                profile_image_url:
                  "http://pbs.twimg.com/profile_images/1505252903400853504/rrR5ibGq_normal.jpg",
                profile_image_url_https:
                  "https://pbs.twimg.com/profile_images/1505252903400853504/rrR5ibGq_normal.jpg",
                profile_banner_url:
                  "https://pbs.twimg.com/profile_banners/88138010/1628526976",
                profile_link_color: "0099CC",
                profile_sidebar_border_color: "FFF8AD",
                profile_sidebar_fill_color: "F6FFD1",
                profile_text_color: "333333",
                profile_use_background_image: true,
                has_extended_profile: true,
                default_profile: false,
                default_profile_image: false,
                following: null,
                follow_request_sent: null,
                notifications: null,
                translator_type: "none",
                withheld_in_countries: [],
              },
            },
          },
        ],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 837172729010847700,
        id_str: "837172729010847744",
        name: "अजमेरी",
        screen_name: "ajmeripoet",
        location: "बद्दुआ मै\n\n",
        description: "chant and be happy ☺\n\nhttps://t.co/PR7DvhJ3fl",
        url: "https://t.co/HvQWQqI93A",
        entities: {
          url: {
            urls: [
              {
                url: "https://t.co/HvQWQqI93A",
                expanded_url:
                  "https://instagram.com/ajmeripoet?utm_medium=copy_link",
                display_url: "instagram.com/ajmeripoet?utm…",
                indices: [0, 23],
              },
            ],
          },
          description: {
            urls: [
              {
                url: "https://t.co/PR7DvhJ3fl",
                expanded_url:
                  "https://mobile.twitter.com/search?lang=en&q=(from%3Aajmeripoet)%20-filter%3Areplies&src=typed_query",
                display_url: "mobile.twitter.com/search?lang=en…",
                indices: [22, 45],
              },
            ],
          },
        },
        protected: false,
        followers_count: 8022,
        friends_count: 541,
        listed_count: 24,
        created_at: "Thu Mar 02 05:28:27 +0000 2017",
        favourites_count: 96512,
        utc_offset: null,
        time_zone: null,
        geo_enabled: true,
        verified: false,
        statuses_count: 117439,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1538188249893838848/0N0V-t6E_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1538188249893838848/0N0V-t6E_normal.jpg",
        profile_banner_url:
          "https://pbs.twimg.com/profile_banners/837172729010847744/1653298432",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: false,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      retweeted_status: {
        created_at: "Fri Jun 17 19:21:01 +0000 2022",
        id: 1537877998514237400,
        id_str: "1537877998514237442",
        full_text:
          "mumbai indians \nbefore 2022                      in 2022 https://t.co/EWsWU6y5Wq",
        truncated: false,
        display_text_range: [0, 56],
        entities: {
          hashtags: [],
          symbols: [],
          user_mentions: [],
          urls: [],
          media: [
            {
              id: 1537877966469726200,
              id_str: "1537877966469726208",
              indices: [57, 80],
              media_url:
                "http://pbs.twimg.com/ext_tw_video_thumb/1537877966469726208/pu/img/jPdRVIUZXPi48w3Q.jpg",
              media_url_https:
                "https://pbs.twimg.com/ext_tw_video_thumb/1537877966469726208/pu/img/jPdRVIUZXPi48w3Q.jpg",
              url: "https://t.co/EWsWU6y5Wq",
              display_url: "pic.twitter.com/EWsWU6y5Wq",
              expanded_url:
                "https://twitter.com/dhaikilokatweet/status/1537877998514237442/video/1",
              type: "photo",
              sizes: {
                thumb: {
                  w: 150,
                  h: 150,
                  resize: "crop",
                },
                small: {
                  w: 680,
                  h: 680,
                  resize: "fit",
                },
                large: {
                  w: 1080,
                  h: 1080,
                  resize: "fit",
                },
                medium: {
                  w: 1080,
                  h: 1080,
                  resize: "fit",
                },
              },
            },
          ],
        },
        extended_entities: {
          media: [
            {
              id: 1537877966469726200,
              id_str: "1537877966469726208",
              indices: [57, 80],
              media_url:
                "http://pbs.twimg.com/ext_tw_video_thumb/1537877966469726208/pu/img/jPdRVIUZXPi48w3Q.jpg",
              media_url_https:
                "https://pbs.twimg.com/ext_tw_video_thumb/1537877966469726208/pu/img/jPdRVIUZXPi48w3Q.jpg",
              url: "https://t.co/EWsWU6y5Wq",
              display_url: "pic.twitter.com/EWsWU6y5Wq",
              expanded_url:
                "https://twitter.com/dhaikilokatweet/status/1537877998514237442/video/1",
              type: "video",
              sizes: {
                thumb: {
                  w: 150,
                  h: 150,
                  resize: "crop",
                },
                small: {
                  w: 680,
                  h: 680,
                  resize: "fit",
                },
                large: {
                  w: 1080,
                  h: 1080,
                  resize: "fit",
                },
                medium: {
                  w: 1080,
                  h: 1080,
                  resize: "fit",
                },
              },
              video_info: {
                aspect_ratio: [1, 1],
                duration_millis: 10495,
                variants: [
                  {
                    bitrate: 1280000,
                    content_type: "video/mp4",
                    url: "https://video.twimg.com/ext_tw_video/1537877966469726208/pu/vid/720x720/rubQMRDlOrmvdaKt.mp4?tag=12",
                  },
                  {
                    content_type: "application/x-mpegURL",
                    url: "https://video.twimg.com/ext_tw_video/1537877966469726208/pu/pl/VOk24PSxFWAyX7MU.m3u8?tag=12&container=fmp4",
                  },
                  {
                    bitrate: 832000,
                    content_type: "video/mp4",
                    url: "https://video.twimg.com/ext_tw_video/1537877966469726208/pu/vid/540x540/iwQ5W7y1ABn1NXsC.mp4?tag=12",
                  },
                  {
                    bitrate: 432000,
                    content_type: "video/mp4",
                    url: "https://video.twimg.com/ext_tw_video/1537877966469726208/pu/vid/320x320/Hb-eo0MYZjxyxHJq.mp4?tag=12",
                  },
                ],
              },
              additional_media_info: {
                monetizable: false,
              },
            },
          ],
        },
        metadata: {
          iso_language_code: "en",
          result_type: "recent",
        },
        source:
          '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
          id: 88138010,
          id_str: "88138010",
          name: "Arun Lol",
          screen_name: "dhaikilokatweet",
          location: "",
          description: "save RR fans only 3 left https://t.co/yxNp6zSgSz",
          url: null,
          entities: {
            description: {
              urls: [
                {
                  url: "https://t.co/yxNp6zSgSz",
                  expanded_url: "http://instagram.com/arun__lol",
                  display_url: "instagram.com/arun__lol",
                  indices: [25, 48],
                },
              ],
            },
          },
          protected: false,
          followers_count: 41618,
          friends_count: 543,
          listed_count: 135,
          created_at: "Sat Nov 07 07:28:21 +0000 2009",
          favourites_count: 56790,
          utc_offset: null,
          time_zone: null,
          geo_enabled: true,
          verified: false,
          statuses_count: 99621,
          lang: null,
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: "FFF04D",
          profile_background_image_url:
            "http://abs.twimg.com/images/themes/theme19/bg.gif",
          profile_background_image_url_https:
            "https://abs.twimg.com/images/themes/theme19/bg.gif",
          profile_background_tile: false,
          profile_image_url:
            "http://pbs.twimg.com/profile_images/1505252903400853504/rrR5ibGq_normal.jpg",
          profile_image_url_https:
            "https://pbs.twimg.com/profile_images/1505252903400853504/rrR5ibGq_normal.jpg",
          profile_banner_url:
            "https://pbs.twimg.com/profile_banners/88138010/1628526976",
          profile_link_color: "0099CC",
          profile_sidebar_border_color: "FFF8AD",
          profile_sidebar_fill_color: "F6FFD1",
          profile_text_color: "333333",
          profile_use_background_image: true,
          has_extended_profile: true,
          default_profile: false,
          default_profile_image: false,
          following: null,
          follow_request_sent: null,
          notifications: null,
          translator_type: "none",
          withheld_in_countries: [],
        },
        geo: null,
        coordinates: null,
        place: null,
        contributors: null,
        is_quote_status: false,
        retweet_count: 13,
        favorite_count: 52,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: "en",
      },
      is_quote_status: false,
      retweet_count: 13,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      possibly_sensitive: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 12:48:48 +0000 2022",
      id: 1538141679638630400,
      id_str: "1538141679638630400",
      full_text:
        "@TheGvs0 @Ben_Wisden Please don't call Mumbai Indians as minnows nor Mumbai grounds are his home grounds... Don't disrespect MI",
      truncated: false,
      display_text_range: [21, 127],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "TheGvs0",
            name: "Zitin",
            id: 249042463,
            id_str: "249042463",
            indices: [0, 8],
          },
          {
            screen_name: "Ben_Wisden",
            name: "Ben Gardner",
            id: 717677883704143900,
            id_str: "717677883704143873",
            indices: [9, 20],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: 1537809207063646200,
      in_reply_to_status_id_str: "1537809207063646208",
      in_reply_to_user_id: 249042463,
      in_reply_to_user_id_str: "249042463",
      in_reply_to_screen_name: "TheGvs0",
      user: {
        id: 1365218872647774200,
        id_str: "1365218872647774211",
        name: "tweetersaahab",
        screen_name: "tweeterpanchi",
        location: "",
        description: "बातें खरी-खोटी,\nसुनने की क्षमता रखिये ||",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 43,
        friends_count: 531,
        listed_count: 8,
        created_at: "Fri Feb 26 08:36:02 +0000 2021",
        favourites_count: 9127,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 4430,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1365219739442683910/VTr5DUW-_normal.jpg",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1365219739442683910/VTr5DUW-_normal.jpg",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 12:31:34 +0000 2022",
      id: 1538137342363451400,
      id_str: "1538137342363451392",
      full_text:
        "RT @mihirkotecha: Inspiration to 1.35 Billion Indians ,Welcomed Hon. Prime Minister Shri @narendramodi ji in #Mumbai today #JaiHind #JaiMah…",
      truncated: false,
      display_text_range: [0, 140],
      entities: {
        hashtags: [
          {
            text: "Mumbai",
            indices: [109, 116],
          },
          {
            text: "JaiHind",
            indices: [123, 131],
          },
        ],
        symbols: [],
        user_mentions: [
          {
            screen_name: "mihirkotecha",
            name: "Mihir Kotecha",
            id: 263089157,
            id_str: "263089157",
            indices: [3, 16],
          },
          {
            screen_name: "narendramodi",
            name: "Narendra Modi",
            id: 18839785,
            id_str: "18839785",
            indices: [89, 102],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="http://twitter.com/download/android" rel="nofollow">Twitter for Android</a>',
      in_reply_to_status_id: null,
      in_reply_to_status_id_str: null,
      in_reply_to_user_id: null,
      in_reply_to_user_id_str: null,
      in_reply_to_screen_name: null,
      user: {
        id: 1505584923901829000,
        id_str: "1505584923901829121",
        name: "Nilesh Pattani",
        screen_name: "NileshPattani9",
        location: "",
        description: "",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 16,
        friends_count: 16,
        listed_count: 0,
        created_at: "Sun Mar 20 16:40:24 +0000 2022",
        favourites_count: 222,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 221,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://pbs.twimg.com/profile_images/1505585057968562176/Gkl37ypg_normal.png",
        profile_image_url_https:
          "https://pbs.twimg.com/profile_images/1505585057968562176/Gkl37ypg_normal.png",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: false,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      retweeted_status: {
        created_at: "Tue Jun 14 15:10:34 +0000 2022",
        id: 1536727806976987100,
        id_str: "1536727806976987136",
        full_text:
          "Inspiration to 1.35 Billion Indians ,Welcomed Hon. Prime Minister Shri @narendramodi ji in #Mumbai today #JaiHind #JaiMaharashtra https://t.co/lT9wxwkGs4",
        truncated: false,
        display_text_range: [0, 129],
        entities: {
          hashtags: [
            {
              text: "Mumbai",
              indices: [91, 98],
            },
            {
              text: "JaiHind",
              indices: [105, 113],
            },
            {
              text: "JaiMaharashtra",
              indices: [114, 129],
            },
          ],
          symbols: [],
          user_mentions: [
            {
              screen_name: "narendramodi",
              name: "Narendra Modi",
              id: 18839785,
              id_str: "18839785",
              indices: [71, 84],
            },
          ],
          urls: [],
          media: [
            {
              id: 1536727795291852800,
              id_str: "1536727795291852803",
              indices: [130, 153],
              media_url: "http://pbs.twimg.com/media/FVONybLXEAMP8y2.jpg",
              media_url_https:
                "https://pbs.twimg.com/media/FVONybLXEAMP8y2.jpg",
              url: "https://t.co/lT9wxwkGs4",
              display_url: "pic.twitter.com/lT9wxwkGs4",
              expanded_url:
                "https://twitter.com/mihirkotecha/status/1536727806976987136/photo/1",
              type: "photo",
              sizes: {
                thumb: {
                  w: 150,
                  h: 150,
                  resize: "crop",
                },
                small: {
                  w: 680,
                  h: 468,
                  resize: "fit",
                },
                medium: {
                  w: 1200,
                  h: 826,
                  resize: "fit",
                },
                large: {
                  w: 1280,
                  h: 881,
                  resize: "fit",
                },
              },
            },
          ],
        },
        extended_entities: {
          media: [
            {
              id: 1536727795291852800,
              id_str: "1536727795291852803",
              indices: [130, 153],
              media_url: "http://pbs.twimg.com/media/FVONybLXEAMP8y2.jpg",
              media_url_https:
                "https://pbs.twimg.com/media/FVONybLXEAMP8y2.jpg",
              url: "https://t.co/lT9wxwkGs4",
              display_url: "pic.twitter.com/lT9wxwkGs4",
              expanded_url:
                "https://twitter.com/mihirkotecha/status/1536727806976987136/photo/1",
              type: "photo",
              sizes: {
                thumb: {
                  w: 150,
                  h: 150,
                  resize: "crop",
                },
                small: {
                  w: 680,
                  h: 468,
                  resize: "fit",
                },
                medium: {
                  w: 1200,
                  h: 826,
                  resize: "fit",
                },
                large: {
                  w: 1280,
                  h: 881,
                  resize: "fit",
                },
              },
            },
          ],
        },
        metadata: {
          iso_language_code: "en",
          result_type: "recent",
        },
        source:
          '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>',
        in_reply_to_status_id: null,
        in_reply_to_status_id_str: null,
        in_reply_to_user_id: null,
        in_reply_to_user_id_str: null,
        in_reply_to_screen_name: null,
        user: {
          id: 263089157,
          id_str: "263089157",
          name: "Mihir Kotecha",
          screen_name: "mihirkotecha",
          location: "Mulund , Mumbai",
          description:
            "MLA Mulund ,BJP Maharastra State Treasurer ,Executive president #CAI Founder member of #VIMU",
          url: "https://t.co/5o52xGsvtD",
          entities: {
            url: {
              urls: [
                {
                  url: "https://t.co/5o52xGsvtD",
                  expanded_url: "http://mihirkotecha.com",
                  display_url: "mihirkotecha.com",
                  indices: [0, 23],
                },
              ],
            },
            description: {
              urls: [],
            },
          },
          protected: false,
          followers_count: 15345,
          friends_count: 1401,
          listed_count: 26,
          created_at: "Wed Mar 09 10:46:45 +0000 2011",
          favourites_count: 4328,
          utc_offset: null,
          time_zone: null,
          geo_enabled: true,
          verified: true,
          statuses_count: 3375,
          lang: null,
          contributors_enabled: false,
          is_translator: false,
          is_translation_enabled: false,
          profile_background_color: "C0DEED",
          profile_background_image_url:
            "http://abs.twimg.com/images/themes/theme1/bg.png",
          profile_background_image_url_https:
            "https://abs.twimg.com/images/themes/theme1/bg.png",
          profile_background_tile: true,
          profile_image_url:
            "http://pbs.twimg.com/profile_images/1278913792647163905/HmAuqHac_normal.jpg",
          profile_image_url_https:
            "https://pbs.twimg.com/profile_images/1278913792647163905/HmAuqHac_normal.jpg",
          profile_banner_url:
            "https://pbs.twimg.com/profile_banners/263089157/1572596127",
          profile_link_color: "0084B4",
          profile_sidebar_border_color: "FFFFFF",
          profile_sidebar_fill_color: "DDEEF6",
          profile_text_color: "333333",
          profile_use_background_image: true,
          has_extended_profile: true,
          default_profile: false,
          default_profile_image: false,
          following: null,
          follow_request_sent: null,
          notifications: null,
          translator_type: "none",
          withheld_in_countries: [],
        },
        geo: null,
        coordinates: null,
        place: {
          id: "7929cea6bd5b32bd",
          url: "https://api.twitter.com/1.1/geo/id/7929cea6bd5b32bd.json",
          place_type: "city",
          name: "Mumbai",
          full_name: "Mumbai, India",
          country_code: "IN",
          country: "India",
          contained_within: [],
          bounding_box: {
            type: "Polygon",
            coordinates: [
              [
                [72.74484, 18.845343],
                [73.003648, 18.845343],
                [73.003648, 19.502937],
                [72.74484, 19.502937],
              ],
            ],
          },
          attributes: {},
        },
        contributors: null,
        is_quote_status: false,
        retweet_count: 178,
        favorite_count: 1910,
        favorited: false,
        retweeted: false,
        possibly_sensitive: false,
        lang: "en",
      },
      is_quote_status: false,
      retweet_count: 178,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
    {
      created_at: "Sat Jun 18 12:14:07 +0000 2022",
      id: 1538132951845978000,
      id_str: "1538132951845978112",
      full_text:
        "@varunsingh77899 @mufaddal_vohra Kid, TKR is most successful team in whole world won 4 titles in just 8 years better than Mumbai Indians and Chennai. So shut up u kid",
      truncated: false,
      display_text_range: [33, 166],
      entities: {
        hashtags: [],
        symbols: [],
        user_mentions: [
          {
            screen_name: "varunsingh77899",
            name: "CSK hype bot",
            id: 1534788111711907800,
            id_str: "1534788111711907840",
            indices: [0, 16],
          },
          {
            screen_name: "mufaddal_vohra",
            name: "Mufaddal Vohra",
            id: 3133996860,
            id_str: "3133996860",
            indices: [17, 32],
          },
        ],
        urls: [],
      },
      metadata: {
        iso_language_code: "en",
        result_type: "recent",
      },
      source:
        '<a href="https://mobile.twitter.com" rel="nofollow">Twitter Web App</a>',
      in_reply_to_status_id: 1538104646891282400,
      in_reply_to_status_id_str: "1538104646891282432",
      in_reply_to_user_id: 1534788111711907800,
      in_reply_to_user_id_str: "1534788111711907840",
      in_reply_to_screen_name: "varunsingh77899",
      user: {
        id: 1504741627536937000,
        id_str: "1504741627536936961",
        name: "Abhishek Kr",
        screen_name: "Abhishe98913736",
        location: "",
        description: "Hardworking",
        url: null,
        entities: {
          description: {
            urls: [],
          },
        },
        protected: false,
        followers_count: 1,
        friends_count: 7,
        listed_count: 0,
        created_at: "Fri Mar 18 08:49:12 +0000 2022",
        favourites_count: 21,
        utc_offset: null,
        time_zone: null,
        geo_enabled: false,
        verified: false,
        statuses_count: 542,
        lang: null,
        contributors_enabled: false,
        is_translator: false,
        is_translation_enabled: false,
        profile_background_color: "F5F8FA",
        profile_background_image_url: null,
        profile_background_image_url_https: null,
        profile_background_tile: false,
        profile_image_url:
          "http://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
        profile_image_url_https:
          "https://abs.twimg.com/sticky/default_profile_images/default_profile_normal.png",
        profile_link_color: "1DA1F2",
        profile_sidebar_border_color: "C0DEED",
        profile_sidebar_fill_color: "DDEEF6",
        profile_text_color: "333333",
        profile_use_background_image: true,
        has_extended_profile: true,
        default_profile: true,
        default_profile_image: true,
        following: null,
        follow_request_sent: null,
        notifications: null,
        translator_type: "none",
        withheld_in_countries: [],
      },
      geo: null,
      coordinates: null,
      place: null,
      contributors: null,
      is_quote_status: false,
      retweet_count: 0,
      favorite_count: 0,
      favorited: false,
      retweeted: false,
      lang: "en",
    },
  ];
  return (
    <div className={styles.socials}>
      <div className={styles.bg}>
        <img src="https://i.ibb.co/1zFGLBc/Wankhede-ICC-WCF.jpg" alt="" />
      </div>

      <Header />

      <div className={styles.main}>
        <p className={styles.heroheading}>Mi Social</p>
        <div className={styles.wrapper}>
          {data.map((tweet) => {
            return (
              <div className={styles.tweet}>
                <img src={tweet.user.profile_image_url} alt="" />
                <div className={styles.right}>
                  <p>{tweet.user.name}</p>
                  <p>@{tweet.user.screen_name}</p>
                  <p>{tweet.full_text}</p>
                  <p>
                    {tweet.created_at.split(" ")[1] +
                      " " +
                      new Date(tweet.created_at).getDate()}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
